# Generated by Django 2.2.1 on 2019-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('Userid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserDomain', models.TextField()),
                ('UserName', models.TextField()),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
